server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: H4aP6ZTaKquQrqVZ9JT9mkFpJwX83xKBRMbbdDbIgr4=
          jws-algorithms: HS256
          # ??? ????JWK URI
          #jwk-set-uri: https://localhost:8080/ #https://auth.example.com/.well-known/jwks.json
          # ??
          # public-key-location: classpath:public.pem
  application:
    name: SpringPratice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    name: root
    username: root
    password: jinny837
    url: jdbc:postgresql://localhost:54321/mydatabase
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
  quartz:
    auto-startup: true
    scheduler-name: QuartzScheduler
    job-store-type: jdbc
    jdbc:
      schema: classpath:quartz.sql
      initialize-schema: never
    properties:
      org:
        quartz:
          threadPool:
            threadNamePrefix: QuartzScheduler
            threadCount: 10
            class: org.quartz.simpl.SimpleThreadPool
          scheduler:
            instanceId: AUTO
            instance-name: quartzScheduler
          jobStore:
            useProperties: false
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            dataSource: quartzDataSource
            tablePrefix: QRTZ_
          #  isClustered: true
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: quartz
  endpoint:
    shutdown:
      enabled: true

security:
  jwt:
    secret: H4aP6ZTaKquQrqVZ9JT9mkFpJwX83xKBRMbbdDbIgr4= #"H4aP6ZTaKquQrqVZ9JT9mkFpJwX83xKBRMbbdDbIgr4="   # Base64("base64-encode-key-example")
    expire-length: 3600000