@baseUrl = http://localhost:8080
@authorization = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaW5ueSIsInJvbGVzIjpbIlJPTEVfUk9MRV9VU0VSIl0sImlhdCI6MTc0NTA2OTY4MSwiZXhwIjoxNzQ1MDczMjgxfQ.sXX95L-wC5TjkQZ_rZUvuJeVH8hpzbVGejeM6UOmuxg

### Create a new Quartz Job
POST {{baseUrl}}/api/jobs
Authorization: Bearer {{authorization}}
Content-Type: application/json

{
  "jobName": "CronJob",
  "jobGroup": "DEFAULT",
  "cronExpression": "0/30 * * * * ?",
  "jobClass": "com.basic.springpratice.domain.schedul.job.CronJob",
  "jobData": {
    "param1": "value1",
    "param2": 123
  }
}

### Delete a Quartz Job
DELETE {{baseUrl}}/api/jobs/DEFAULT/CronJob
Authorization: Bearer {{authorization}}
Content-Type: application/json

### Pause a Quartz Job
POST {{baseUrl}}/api/jobs/DEFAULT/CronJob/pause
Authorization: Bearer {{authorization}}
Content-Type: application/json

### Resume a Quartz Job
POST {{baseUrl}}/api/jobs/DEFAULT/CronJob/resume
Authorization: Bearer {{authorization}}
Content-Type: application/json

### Retrieve registered job and trigger groups
GET {{baseUrl}}/actuator/quartz

### Retrieve registered job names for all groups
GET {{baseUrl}}/actuator/quartz/jobs

### Retrieve registered trigger names for all groups
GET {{baseUrl}}/actuator/quartz/triggers

### Retrieve overview of a job group (e.g., 'samples')
GET {{baseUrl}}/actuator/quartz/jobs/samples

### Retrieve overview of a trigger group (e.g., 'DEFAULT')
GET {{baseUrl}}/actuator/quartz/triggers/DEFAULT

### Retrieve details of a job (e.g., 'jobOne' in 'samples')
GET {{baseUrl}}/actuator/quartz/jobs/samples/jobOne

### Retrieve details of a trigger (e.g., 'example' in 'samples')
GET {{baseUrl}}/actuator/quartz/triggers/samples/example
